### ISSUE TITLE
Jika ingin chain lebih dari 2x

### ISSUE THREAD

**Issue by hendrorahmat** [hilmanrdn/pirlo-db#1]
public function getWhere($bridge)
    {
        $this->_attr = '';
        $this->_params = [];
        $this->_bridge[] = $bridge;
        $i = 1;
        foreach ($this->_prevData as $prevData) {
            $this->_attr .= $prevData['column'].' '.$prevData['operator']." ?";
            $this->_params[] .= $prevData['value'];

```
        if ($i < count($this->_prevData)) {
            $this->_attr .= $this->_bridge[$i];
        }

        $i++;
    }
    return $this;
}
```

**Comment by hilmanski** [comment]
terima kasih laporannya, bisa dilihat updateannya disini [tutorial](https://sekolahkoding.com/kelas/membuat-kelas-abstrak-pdo-database) .

Sekedar info, kalo issue tambahakan keterangan laporan errornya apa dan dimana, biar yang lain juga tahu :D ,terima kasih!

**Comment by hendrorahmat** [comment]
Kalo ada masalah lagi, saya tanya lewat mana mas,? Forum atau gimana
enaknya? Maaf juga udah langgar peraturan hehehe
